### ISSUE TITLE
Setup script fails after failing to load source for OpenXR during ALVR build process with PKGBUILD

### ISSUE THREAD

**Issue by ryangwsimmons** [alvr-org/ALVR-Distrobox-Linux-Guide#16]
The title basically describes the issue. At (what appears to be, anyway) the start of phase 4 in the Distrobox setup script, during the build process for ALVR using Paru, Cargo seems to be unable to pull the source for the OpenXR repo given in the Cargo.toml for alvr_client_openxr. This causes the build as a whole to fail, which ends the setup script.

Here is my full [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13781536/setup.log).

Let me know if there's any additional info you want from me, I'm happy to help.

**Comment by Farm8763** [comment]
Yeah, I'm running into the same issue. Looks like it's because:

1. this [paru command](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/blob/246c784b1b36d318ac54cd384c69db2fbaee4239/setup-phase-4.sh#L92) calls 
2. [this AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=alvr#n19) 
3. which fetches v20.5.0 of ALVR [that has a link that redirects](https://github.com/alvr-org/ALVR/blob/4e1c56f61e9ba64a794fdcfe85b50b0370b6e793/alvr/client_openxr/Cargo.toml#L20) to the ALVR github, but the code doesn't follow the link and should be [https://github.com/alvr-org/openxrs](https://github.com/alvr-org/openxrs)?


Ah, looks like it's fixed in main https://github.com/alvr-org/ALVR/commit/36f74835b567d203e625c18b8a5c1c53588c72d2 so next release should be good

**Comment by Farm8763** [comment]
Can confirm it's working in main. I was able to run the broken piece by changing the PKGBUILD file to use alvr main branch. I used the `--fm vim` flag as per below (pretty janky test)
```
[farm@arch-alvr ALVR-Distrobox-Linux-Guide]$ paru -q --noprogressbar -S rust alvr --fm vim --assume-installed vulkan-driver --assume-installed lib32-vulkan-driver
...
Aur (1)   Old Version  New Version    Make Only
aur/alvr               20.5.0-1       No

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
:: Accept changes? [Y/n]: 

---------------------
#changed the PKGBUILD file then continued
^Z
[1]+  Stopped                 paru -q --noprogressbar -S rust alvr --fm vim --assume-installed vulkan-driver --assume-installed lib32-vulkan-driver
[farm@arch-alvr ALVR-Distrobox-Linux-Guide]$ vim /home/farm/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.cache/paru/clone/alvr/PKGBUILD 
[farm@arch-alvr ALVR-Distrobox-Linux-Guide]$ fg
----------------------


paru -q --noprogressbar -S rust alvr --fm vim --assume-installed vulkan-driver --assume-installed lib32-vulkan-driver
y
fetching devel info...
==> Making package: alvr 20.5.0-1 (Mon 01 Jan 2024 09:24:02 PM EST)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Updating alvr git repo...
==> Validating source files with md5sums...
    alvr ... Skipped
==> Making package: alvr 20.5.0-1 (Mon 01 Jan 2024 09:24:03 PM EST)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Updating alvr git repo...
==> Validating source files with md5sums...
    alvr ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of alvr git repo...
Cloning into 'alvr'...
done.
==> Starting prepare()...
    Updating crates.io index
    Updating git repository `https://github.com/alvr-org/openxrs`
    Updating git submodule `https://github.com/KhronosGroup/OpenXR-SDK.git`
  Downloaded xshell-macros v0.2.5

```

**Comment by Meister1593** [comment]
I updated current repository with many changes and redirected it to alvr-git for now, it should compile successfully for now
Open new issue if you still have issues with that or something else.
